name: cfDNApipe
channels:
  - dranew
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _r-mutex=1.0.1=anacondar_1
  - adapterremoval=2.3.1=hb7ba0dd_1
  - bcftools=1.9=h68d8f2e_9
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.33.1=he1b5a44_7
  - binutils_linux-64=2.33.1=h9595d00_17
  - bioconductor-dnacopy=1.60.0=r36h6e990d7_0
  - biopython=1.76=py36h516909a_0
  - bismark=0.23.0=0
  - blas=2.17=openblas
  - bowtie2=2.4.2=py36h5202f60_1
  - bwidget=1.9.14=ha770c72_0
  - bx-python=0.8.9=py36h5e0341f_2
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.8=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - centrifuge=1.0.4_beta=py36pl526he941832_2
  - certifi=2020.12.5=py36h5fab9bb_1
  - cnvkit=0.9.6=py36_1
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.10=he6710b0_2
  - fastqc=0.11.9=0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.2=py36h5fab9bb_2
  - gatk4=4.1.9.0=py39_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_17
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_17
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_17
  - harfbuzz=1.9.0=he243708_1001
  - hisat2=2.2.1=he1b5a44_2
  - hmmcopy_utils=0.0.1=1
  - htslib=1.9=h244ad75_9
  - icu=58.2=he6710b0_3
  - joblib=0.17.0=py_0
  - jpeg=9b=habf39ab_1
  - kiwisolver=1.2.0=py36hfd86e86_0
  - krb5=1.16.4=h2fd8d38_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.68.0=hda55be3_0
  - libdeflate=1.3=h516909a_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libopenblas=0.3.10=h5a2b251_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=11.0.0=hfc4b9b4_1
  - lz4-c=1.9.2=heb0550a_3
  - lzo=2.10=h516909a_1000
  - make=4.3=hd18ef5c_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py36h817c723_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.19.1=py36h30dfecb_0
  - numpy-base=1.19.1=py36h75fe3a5_0
  - olefile=0.46=py36_0
  - openjdk=8.0.265=h516909a_0
  - openssl=1.1.1i=h7f98852_0
  - pandas=1.1.3=py36he6710b0_0
  - pango=1.42.4=h049681c_0
  - patsy=0.5.1=py36_0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h36c2ea0_1008
  - pillow=8.0.0=py36h9a89aac_0
  - pip=20.3.3=py36h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pomegranate=0.13.3=py36hdb11119_0
  - pybedtools=0.8.1=py36h5202f60_2
  - pyfaidx=0.5.9.2=pyh3252c3a_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pysam=0.15.3=py36hbcae180_3
  - python=3.6.10=h191fe78_1
  - python-box=5.2.0=pyhd8ed1ab_0
  - python-dateutil=2.8.1=py_0
  - python-lzo=1.12=py36h864e7bf_1001
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py36he6145b8_1
  - qt=5.9.7=h5867ecd_1
  - qualimap=2.2.2a=1
  - r-base=3.6.0=hce969dd_0
  - r-cghflasso=0.2_1=r36h6e990d7_1004
  - readline=7.0=hf8c457e_1001
  - reportlab=3.5.59=py36h3e18861_0
  - ruamel.yaml=0.16.12=py36h7b6447c_1
  - ruamel.yaml.clib=0.2.2=py36h7b6447c_0
  - samtools=1.6=h244ad75_5
  - scikit-learn=0.23.2=py36h0573a6f_0
  - scipy=1.5.2=py36habc2bb6_0
  - seaborn=0.11.0=py_0
  - setuptools=51.0.0=py36h06a4308_2
  - sip=4.19.24=py36he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.0=py36h7b6447c_0
  - tbb=2020.2=hc9558a2_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tktable=2.10=hb7b940f_3
  - toml=0.10.1=py_0
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.50.2=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yattag=1.13.2=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - cfdnapipe

